### ISSUE TITLE
Opening Particular Project with Windows 10

### ISSUE THREAD

**Issue by saldanhag** [populse/populse_db#40]
When I open a project where I previously import the data from the folder data_test/Philips_files/Data_patient of populse_mia, I got the issue :
AttributeError: 'NoneType' object has no attribute 'text'
Meanwhile when I open project_8 from the ressources folder of populse_mia I don't have any issue.
The problem might come from database.py of populse_db line 1559, in the first case self.session.execute(select) is empty and not in the second case.
I worked with windows 10, Python3.8 and populse_db 1.1.2 (master branch from source)

**Comment by servoz** [comment]
Just for help to fix this issue:
- By using the [Crash project](https://mycore.core-cloud.net/index.php/s/l50dj4WV1PlZcwk) (download the zip file, unzip it, then in mia File > Open project ; browse to the unziped Crash project ; click Choose button): mia crash with the following exception:
```
Traceback (most recent call last):
  File "C:\Users\Guillaume\Desktop\Installation\populse_mia\python\populse_mia\user_interface\main_window.py", line 575, in open_project_pop_up
    self.switch_project(file_name, self.exPopup.name)
  File "C:\Users\Guillaume\Desktop\Installation\populse_mia\python\populse_mia\user_interface\main_window.py", line 992, in switch_project
    self.update_project(file_path)
  File "C:\Users\Guillaume\Desktop\Installation\populse_mia\python\populse_mia\user_interface\main_window.py", line 1146, in update_project
    self.data_browser.table_data.update_table()  # Table updated
  File "C:\Users\Guillaume\Desktop\Installation\populse_mia\python\populse_mia\user_interface\data_browser\data_browser.py", line 2296, in update_table
    self.update_colors()
  File "C:\Users\Guillaume\Desktop\Installation\populse_mia\python\populse_mia\user_interface\data_browser\data_browser.py", line 2152, in update_colors
    scans = [self.item(row, 0).text() for row in range(self.rowCount())]
  File "C:\Users\Guillaume\Desktop\Installation\populse_mia\python\populse_mia\user_interface\data_browser\data_browser.py", line 2152, in <listcomp>
    scans = [self.item(row, 0).text() for row in range(self.rowCount())]
AttributeError: 'NoneType' object has no attribute 'text'
```

- By using the [NoCrash project](https://mycore.core-cloud.net/index.php/s/S3rx1EQ9cW6xnq7)  (download the zip file, unzip it, then in mia File > Open project ; browse to the unziped NoCrash project ; click Choose button): mia loads the NoCrash project without any problem !!!

However, in the populse_db.database module, filter_documents() method of the DatabaseSession class, if the `filter_query` is removed for the selection, i.e.:
``` 
else:
            select = self.metadata.tables[self.name_to_valid_column_name(collection)].select(
                filter_query)
            python_filter = None
```
is changed to 
 ```
 else:
            #select = self.metadata.tables[self.name_to_valid_column_name(collection)].select(
            #    filter_query)
            #python_filter = None
            select = self.metadata.tables[self.name_to_valid_column_name(collection)].select()
            python_filter = None
```
then,  mia loads the Crash project without any problem !!!

windows 10 Professionnel, all the populse branchs on master, usual  python third party libraries

**Comment by denisri** [comment]
I can reproduce the problem using the "Crash project". This project has been built on windows, and contains filenames with directories separated by backslashes. It seems that slashes should be "doubled" (escaped) in database requests:
In data_browser.py, fill_cells_update_table(), l 1398, there is a database request looking for filenames:
```
            req = '%s IN [%s]' \
                % (primary_key, ', '.join(['"%s"' % x.replace('"', '\"')
                                           for x in self.scans_to_visualize]))
            scans = dbs.filter_documents(COLLECTION_CURRENT, req)
```
If I print "self.scans_to_visualize", I read:
```
['data\\raw_data\\alej170316-IRMFonct.+perfusion-2016-03-17083444-0-T13DSENSE-T1TFE-000425.000.nii', 'data\\raw_data\\alej170316-IRMFonct.+perfusion-2016-03-17083444-1-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii']
```
If I print "req", I read:
```
FileName IN ["data\raw_data\alej170316-IRMFonct.+perfusion-2016-03-17083444-0-T13DSENSE-T1TFE-000425.000.nii", "data\raw_data\alej170316-IRMFonct.+perfusion-2016-03-17083444-1-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii"]
```
The slashes are not doubled in the request as expected in the database.
If I replace the above code line with:
```
            req = '%s IN [%s]' \
                % (primary_key, ', '.join(['"%s"' % x.replace('\\', '\\\\').replace('"', '\"')
                                           for x in self.scans_to_visualize]))
            scans = dbs.filter_documents(COLLECTION_CURRENT, req)
```
then the project opens correctly. Quotes were escaped in the request, but not backslashes - it appears they need too ;)

I let you fix it on your side...

**Comment by denisri** [comment]
Oh after all I will fix it on my side since I will also check what happens with populse_db 2 and the corresponding branch of populse_mia.

**Comment by servoz** [comment]
@denisri  you know what ? I love you ...

**Comment by saldanhag** [comment]
That works for me too now thank you
